/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utilitarios.FundoTela;
import java.awt.GridLayout;
import javax.swing.JFrame;

/**
 *
 * @author jonat
 */
public class Principal extends javax.swing.JFrame {

   FundoTela tela;
   ClienteTela  clientetela;
   FuncionarioTela  functela;
    
    
    public Principal() {
        initComponents();
        //Para a pagina vir maximizada ao abrir 
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //Para instanciar a imagem dentro do objeto
        setLayout(new GridLayout());
        tela = new FundoTela("imagens/pizzaria-logo-01.png");
        getContentPane().add(tela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuItemClientes = new javax.swing.JMenuItem();
        MenuItemFuncionarios = new javax.swing.JMenuItem();
        MenuItemCardapio = new javax.swing.JMenuItem();
        MenuItemEntregador = new javax.swing.JMenuItem();
        MenuCaixa = new javax.swing.JMenu();
        MenuItemPedido = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria_01");

        MenuCadastro.setText("Cadastro");

        MenuItemClientes.setText("Clientes");
        MenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClientesActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemClientes);

        MenuItemFuncionarios.setText("Funcionarios");
        MenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFuncionariosActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemFuncionarios);

        MenuItemCardapio.setText("Cardapio");
        MenuCadastro.add(MenuItemCardapio);

        MenuItemEntregador.setText("Entregador");
        MenuCadastro.add(MenuItemEntregador);

        jMenuBar1.add(MenuCadastro);

        MenuCaixa.setText("Caixa");

        MenuItemPedido.setText("Pedido");
        MenuCaixa.add(MenuItemPedido);

        jMenuBar1.add(MenuCaixa);

        MenuRelatorios.setText("Relatorios");
        jMenuBar1.add(MenuRelatorios);

        jMenu5.setText("Tela de Pedidos");
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Sair");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFuncionariosActionPerformed
        functela = new FuncionarioTela();
        tela.add(functela);
        functela.setVisible(true);
    }//GEN-LAST:event_MenuItemFuncionariosActionPerformed

    private void MenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClientesActionPerformed
        clientetela = new ClienteTela();
        tela.add(clientetela);
        clientetela.setVisible(true);
    }//GEN-LAST:event_MenuItemClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuCaixa;
    private javax.swing.JMenuItem MenuItemCardapio;
    private javax.swing.JMenuItem MenuItemClientes;
    private javax.swing.JMenuItem MenuItemEntregador;
    private javax.swing.JMenuItem MenuItemFuncionarios;
    private javax.swing.JMenuItem MenuItemPedido;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
